<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class CursoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cursos')->insert([
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Informática Para Internet',
                'descricao' => 'Técnico Em Informática Para Internet',
                'carga_horaria' => 360,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Biotecnologia',
                'descricao' => 'Técnico Em Biotecnologia',
                'carga_horaria' => 420,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Celulose E Papel',
                'descricao' => 'Técnico Em Celulose E Papel',
                'carga_horaria' => 380,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Manutenção Automotiva',
                'descricao' => 'Técnico Em Manutenção Automotiva',
                'carga_horaria' => 480,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Petróleo E Gás',
                'descricao' => 'Técnico Em Petróleo E Gás',
                'carga_horaria' => 420,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Petroquímica',
                'descricao' => 'Técnico Em Petroquímica',
                'carga_horaria' => 300,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Produção De Moda',
                'descricao' => 'Técnico Em Produção De Moda',
                'carga_horaria' => 240,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Telecomunicações',
                'descricao' => 'Técnico Em Telecomunicações',
                'carga_horaria' => 200,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Alimentos',
                'descricao' => 'Técnico Em Alimentos',
                'carga_horaria' => 180,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Vestuário',
                'descricao' => 'Técnico Em Vestuário',
                'carga_horaria' => 420,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Análises Químicas',
                'descricao' => 'Técnico Em Análises Químicas',
                'carga_horaria' => 240,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Automação Industrial',
                'descricao' => 'Técnico Em Automação Industrial',
                'carga_horaria' => 260,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Eletroeletrônica',
                'descricao' => 'Técnico Em Eletroeletrônica',
                'carga_horaria' => 200,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Desenvolvimento De Sistemas',
                'descricao' => 'Técnico Em Desenvolvimento De Sistemas',
                'carga_horaria' => 220,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Mecatrônica',
                'descricao' => 'Técnico Em Mecatrônica',
                'carga_horaria' => 300,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Meio Ambiente',
                'descricao' => 'Técnico Em Meio Ambiente',
                'carga_horaria' => 360,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Mineração',
                'descricao' => 'Técnico Em Mineração',
                'carga_horaria' => 420,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Química',
                'descricao' => 'Técnico Em Química',
                'carga_horaria' => 380,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Redes De Computadores',
                'descricao' => 'Técnico Em Redes De Computadores',
                'carga_horaria' => 480,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Eletromecânica',
                'descricao' => 'Técnico Em Eletromecânica',
                'carga_horaria' => 420,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Calçados',
                'descricao' => 'Técnico Em Calçados',
                'carga_horaria' => 300,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Eletrônica',
                'descricao' => 'Técnico Em Eletrônica',
                'carga_horaria' => 240,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Eletrotécnica',
                'descricao' => 'Técnico Em Eletrotécnica',
                'carga_horaria' => 200,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Informática',
                'descricao' => 'Técnico Em Informática',
                'carga_horaria' => 180,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Programação De Jogos Digitais',
                'descricao' => 'Técnico Em Programação De Jogos Digitais',
                'carga_horaria' => 420,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Mecânica',
                'descricao' => 'Técnico Em Mecânica',
                'carga_horaria' => 240,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Soldagem',
                'descricao' => 'Técnico Em Soldagem',
                'carga_horaria' => 260,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Manutenção E Suporte Em Informática',
                'descricao' => 'Técnico Em Manutenção E Suporte Em Informática',
                'carga_horaria' => 200,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Plástico',
                'descricao' => 'Técnico Em Plástico',
                'carga_horaria' => 220,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Têxtil',
                'descricao' => 'Técnico Em Têxtil',
                'carga_horaria' => 300,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Mecânica De Precisão',
                'descricao' => 'Técnico Em Mecânica De Precisão',
                'carga_horaria' => 360,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Logística',
                'descricao' => 'Técnico Em Logística',
                'carga_horaria' => 420,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Administração',
                'descricao' => 'Técnico Em Administração',
                'carga_horaria' => 380,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Refrigeração E Climatização',
                'descricao' => 'Técnico Em Refrigeração E Climatização',
                'carga_horaria' => 480,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Qualidade',
                'descricao' => 'Técnico Em Qualidade',
                'carga_horaria' => 420,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Impressão Offset',
                'descricao' => 'Técnico Em Impressão Offset',
                'carga_horaria' => 300,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Comunicação Visual',
                'descricao' => 'Técnico Em Comunicação Visual',
                'carga_horaria' => 240,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Fabricação Mecânica',
                'descricao' => 'Técnico Em Fabricação Mecânica',
                'carga_horaria' => 200,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Processos Gráficos',
                'descricao' => 'Técnico Em Processos Gráficos',
                'carga_horaria' => 180,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Modelagem Do Vestuário',
                'descricao' => 'Técnico Em Modelagem Do Vestuário',
                'carga_horaria' => 420,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Edificações',
                'descricao' => 'Técnico Em Edificações',
                'carga_horaria' => 240,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Multimídia',
                'descricao' => 'Técnico Em Multimídia',
                'carga_horaria' => 260,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Metalurgia',
                'descricao' => 'Técnico Em Metalurgia',
                'carga_horaria' => 200,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Segurança Do Trabalho',
                'descricao' => 'Técnico Em Segurança Do trabalho',
                'carga_horaria' => 220,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Eletricista Industrial',
                'descricao' => 'Eletricista Industrial',
                'carga_horaria' => 300,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Mecânico De Máquinas Industriais',
                'descricao' => 'Mecânico De Máquinas Industriais',
                'carga_horaria' => 360,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Manutenção De Máquinas Industriais',
                'descricao' => 'Técnico Em Manutenção De Máquinas Industriais',
                'carga_horaria' => 420,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Açúcar E Álcool',
                'descricao' => 'Técnico Em Açúcar E Álcool',
                'carga_horaria' => 380,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Especialização Técnica Em Manutenção Mecânica De Hidrelétricas',
                'descricao' => 'Especialização Técnica Em Manutenção Mecânica De Hidrelétricas',
                'carga_horaria' => 480,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Modelista De Calçados',
                'descricao' => 'Modelista De Calçados',
                'carga_horaria' => 420,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Design Gráfico',
                'descricao' => 'Técnico Em Design Gráfico',
                'carga_horaria' => 300,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Cerâmica',
                'descricao' => 'Técnico Em Cerâmica',
                'carga_horaria' => 240,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Sistemas De Energia Renovável',
                'descricao' => 'Técnico Em Sistemas De Energia Renovável',
                'carga_horaria' => 200,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Design De Calçados',
                'descricao' => 'Técnico Em Design De Calçados',
                'carga_horaria' => 180,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Design De Móveis',
                'descricao' => 'Técnico Em Design De Móveis',
                'carga_horaria' => 420,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Móveis',
                'descricao' => 'Técnico Em Móveis',
                'carga_horaria' => 240,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Confeitaria',
                'descricao' => 'Técnico Em Confeitaria',
                'carga_horaria' => 260,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Panificação',
                'descricao' => 'Técnico Em Panificação',
                'carga_horaria' => 200,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Internet Das Coisas - IoT',
                'descricao' => 'Técnico Em Internet Das Coisas - IoT',
                'carga_horaria' => 220,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Cibersegurança',
                'descricao' => 'Técnico Em Cibersegurança',
                'carga_horaria' => 300,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Cibersistemas Para Automação',
                'descricao' => 'Técnico Em Cibersistemas Para Automação',
                'carga_horaria' => 360,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Instrumentação Industrial',
                'descricao' => 'Técnico Em Instrumentação Industrial',
                'carga_horaria' => 420,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Técnico Em Planejamento E Controle Da Produção',
                'descricao' => 'Técnico Em Planejamento E Controle Da Produção',
                'carga_horaria' => 380,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Assistente Administrativo',
                'descricao' => 'Assistente Administrativo',
                'carga_horaria' => 480,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Marceneiro De Móveis E Esquadrias',
                'descricao' => 'Marceneiro De Móveis E Esquadrias',
                'carga_horaria' => 420,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Eletricista De Instalações Prediais',
                'descricao' => 'Eletricista De Instalações Prediais',
                'carga_horaria' => 300,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Costureiro Sob Medida - Modelagem, Corte E Costura',
                'descricao' => 'Costureiro Sob Medida - Modelagem, Corte E Costura',
                'carga_horaria' => 240,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Operador De Processos De Distribuição Logística',
                'descricao' => 'Operador De Processos De Distribuição Logística',
                'carga_horaria' => 200,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Soldador MAG',
                'descricao' => 'Soldador MAG',
                'carga_horaria' => 180,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Confeccionador De Calçados',
                'descricao' => 'Confeccionador De Calçados',
                'carga_horaria' => 420,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Desenhista Mecânico',
                'descricao' => 'Desenhista Mecânico',
                'carga_horaria' => 240,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Operador De Injetora E Extrusora De Plástico',
                'descricao' => 'Operador De Injetora E Extrusora De Plástico',
                'carga_horaria' => 260,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Eletromecânico De Veículos Leves',
                'descricao' => 'Eletromecânico De Veículos Leves',
                'carga_horaria' => 200,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => (string) Str::uuid(),
                'nome' => 'Construtor De Alvenaria',
                'descricao' => 'Construtor De Alvenaria',
                'carga_horaria' => 220,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
